import { DrinkType, Language } from '@/types/bac';

export const PREDEFINED_DRINKS: Record<DrinkType, { alcoholPercentage: number; volumeMl: number }> = {
  beer: { alcoholPercentage: 5, volumeMl: 330 },
  wine: { alcoholPercentage: 12, volumeMl: 150 },
  spritz: { alcoholPercentage: 8, volumeMl: 200 },
  cocktail: { alcoholPercentage: 15, volumeMl: 150 },
  liqueur: { alcoholPercentage: 30, volumeMl: 50 },
  custom: { alcoholPercentage: 0, volumeMl: 0 },
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  it: {
    appTitle: 'AlcolTracker',
    appSubtitle: 'Know Your Limits',
    
    // Tabs
    tabCalculate: 'Calcolo',
    tabHistory: 'Storico',
    tabChart: 'Grafico',
    tabSettings: 'Impostazioni',
    
    // Calculate page
    weight: 'Peso (kg)',
    gender: 'Sesso',
    male: 'Uomo',
    female: 'Donna',
    predefinedDrinks: 'Alcolici Predefiniti',
    customDrinks: 'Alcolici Personalizzati',
    beer: 'Birra',
    wine: 'Vino',
    spritz: 'Spritz',
    cocktail: 'Cocktail',
    liqueur: 'Liquori',
    glasses: 'bicchieri',
    addCustomDrink: 'Aggiungi Alcolico',
    drinkName: 'Nome',
    alcoholPercentage: 'Gradazione %',
    volumeMl: 'Quantità (ml)',
    saveForFuture: 'Salva per usi futuri',
    timeSinceDrinking: 'Tempo dalla bevuta (opzionale)',
    minutes: 'Minuti',
    hours: 'Ore',
    calculate: 'Calcola BAC',
    
    // Results
    results: 'Risultati',
    bacAtMoment: 'BAC al momento',
    bacAfterTime: 'BAC dopo',
    timeToSober: 'Tempo per tornare sobrio',
    soberIn: 'Sobrio tra',
    alreadySober: 'Già sobrio',
    saveResult: 'Salva Risultato',
    newCalculation: 'Nuovo Calcolo',
    resultSaved: 'Risultato salvato!',
    
    // BAC levels
    sober: 'Sobrio',
    slightImpairment: 'Leggera alterazione',
    mildImpairment: 'Alterazione moderata',
    significantImpairment: 'Alterazione significativa',
    severeImpairment: 'Alterazione grave',
    dangerousLevel: 'Livello pericoloso',
    
    // History
    noHistory: 'Nessun risultato salvato',
    deleteConfirm: 'Eliminare questo risultato?',
    delete: 'Elimina',
    cancel: 'Annulla',
    
    // Chart
    allData: 'Tutti i dati',
    bacAtZeroOnly: 'Solo BAC al momento',
    bacAfterTimeOnly: 'Solo BAC dopo tempo',
    filterByDate: 'Filtra per date',
    specificDate: 'Data specifica',
    dateRange: 'Intervallo di date',
    startDate: 'Data inizio',
    endDate: 'Data fine',
    filterByGender: 'Filtra per sesso',
    allGenders: 'Tutti',
    apply: 'Applica',
    reset: 'Reset',
    noData: 'Nessun dato disponibile',
    
    // Settings
    theme: 'Tema',
    lightTheme: 'Chiaro',
    darkTheme: 'Scuro',
    language: 'Lingua',
    aboutBAC: 'Informazioni su BAC',
    bacInfo: 'Il BAC (Blood Alcohol Concentration) è la concentrazione di alcol nel sangue, misurata in grammi per litro (g/L). Questo valore indica il livello di intossicazione alcolica.',
    howItWorks: 'Come funziona il calcolo',
    formulaInfo: 'Utilizziamo la formula di Widmark:\nBAC = (A / (r × P)) - (β × t)\n\nDove:\n• A = alcol consumato in grammi\n• r = coefficiente di distribuzione (0.68 uomini, 0.55 donne)\n• P = peso corporeo (kg)\n• β = tasso di eliminazione (0.15 g/L/h)\n• t = tempo trascorso (ore)',
    curiosities: 'Curiosità',
    curiositiesInfo: 'Il corpo elimina circa 0.15 g/L di alcol per ora. Questo significa che ci vogliono circa 1-2 ore per metabolizzare un bicchiere standard di bevanda alcolica.',
    privacy: 'Privacy',
    privacyInfo: 'Tutti i dati sono salvati localmente sul tuo dispositivo. Non raccogliamo né condividiamo alcuna informazione personale.',
    terms: 'Termini di servizio',
    termsInfo: 'Questa app è solo a scopo informativo. Non sostituisce il parere medico. Non guidare mai dopo aver bevuto.',
    
    // Errors
    errorWeight: 'Inserisci un peso valido',
    errorNoDrinks: 'Aggiungi almeno un alcolico',
    errorCustomDrink: 'Completa tutti i campi per l\'alcolico personalizzato',
    saveAsDefault: 'Salva come predefinito',
    savedDrinks: 'Alcolici salvati',
    filters: 'Filtri',
    filterByTime: 'Filtra per tempo',
    allDates: 'Tutte le date',
    bacAtMomentOnly: 'Solo BAC al momento',
    bacAfterTimeOnly: 'Solo BAC dopo tempo',
  },
  
  en: {
    appTitle: 'AlcolTracker',
    appSubtitle: 'Know Your Limits',
    
    tabCalculate: 'Calculate',
    tabHistory: 'History',
    tabChart: 'Chart',
    tabSettings: 'Settings',
    
    weight: 'Weight (kg)',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    predefinedDrinks: 'Predefined Drinks',
    customDrinks: 'Custom Drinks',
    beer: 'Beer',
    wine: 'Wine',
    spritz: 'Spritz',
    cocktail: 'Cocktail',
    liqueur: 'Liqueur',
    glasses: 'glasses',
    addCustomDrink: 'Add Drink',
    drinkName: 'Name',
    alcoholPercentage: 'ABV %',
    volumeMl: 'Volume (ml)',
    saveForFuture: 'Save for future use',
    timeSinceDrinking: 'Time since drinking (optional)',
    minutes: 'Minutes',
    hours: 'Hours',
    calculate: 'Calculate BAC',
    
    results: 'Results',
    bacAtMoment: 'BAC at moment',
    bacAfterTime: 'BAC after',
    timeToSober: 'Time to sober up',
    soberIn: 'Sober in',
    alreadySober: 'Already sober',
    saveResult: 'Save Result',
    newCalculation: 'New Calculation',
    resultSaved: 'Result saved!',
    
    sober: 'Sober',
    slightImpairment: 'Slight impairment',
    mildImpairment: 'Mild impairment',
    significantImpairment: 'Significant impairment',
    severeImpairment: 'Severe impairment',
    dangerousLevel: 'Dangerous level',
    
    noHistory: 'No saved results',
    deleteConfirm: 'Delete this result?',
    delete: 'Delete',
    cancel: 'Cancel',
    
    allData: 'All data',
    bacAtZeroOnly: 'BAC at moment only',
    bacAfterTimeOnly: 'BAC after time only',
    filterByDate: 'Filter by date',
    specificDate: 'Specific date',
    dateRange: 'Date range',
    startDate: 'Start date',
    endDate: 'End date',
    filterByGender: 'Filter by gender',
    allGenders: 'All',
    apply: 'Apply',
    reset: 'Reset',
    noData: 'No data available',
    
    theme: 'Theme',
    lightTheme: 'Light',
    darkTheme: 'Dark',
    language: 'Language',
    aboutBAC: 'About BAC',
    bacInfo: 'BAC (Blood Alcohol Concentration) is the concentration of alcohol in blood, measured in grams per liter (g/L). This value indicates the level of alcohol intoxication.',
    howItWorks: 'How calculation works',
    formulaInfo: 'We use the Widmark formula:\nBAC = (A / (r × P)) - (β × t)\n\nWhere:\n• A = alcohol consumed in grams\n• r = distribution coefficient (0.68 males, 0.55 females)\n• P = body weight (kg)\n• β = elimination rate (0.15 g/L/h)\n• t = time elapsed (hours)',
    curiosities: 'Curiosities',
    curiositiesInfo: 'The body eliminates about 0.15 g/L of alcohol per hour. This means it takes about 1-2 hours to metabolize a standard drink.',
    privacy: 'Privacy',
    privacyInfo: 'All data is saved locally on your device. We do not collect or share any personal information.',
    terms: 'Terms of service',
    termsInfo: 'This app is for informational purposes only. It does not replace medical advice. Never drive after drinking.',
    
    errorWeight: 'Enter a valid weight',
    errorNoDrinks: 'Add at least one drink',
    errorCustomDrink: 'Complete all fields for custom drink',
    saveAsDefault: 'Save as default',
    savedDrinks: 'Saved drinks',
    filters: 'Filters',
    filterByTime: 'Filter by time',
    allDates: 'All dates',
    bacAtMomentOnly: 'BAC at moment only',
    bacAfterTimeOnly: 'BAC after time only',
  },
  
  fr: {
    appTitle: 'AlcolTracker',
    appSubtitle: 'Connaissez Vos Limites',
    
    tabCalculate: 'Calcul',
    tabHistory: 'Historique',
    tabChart: 'Graphique',
    tabSettings: 'Paramètres',
    
    weight: 'Poids (kg)',
    gender: 'Sexe',
    male: 'Homme',
    female: 'Femme',
    predefinedDrinks: 'Boissons Prédéfinies',
    customDrinks: 'Boissons Personnalisées',
    beer: 'Bière',
    wine: 'Vin',
    spritz: 'Spritz',
    cocktail: 'Cocktail',
    liqueur: 'Liqueur',
    glasses: 'verres',
    addCustomDrink: 'Ajouter Boisson',
    drinkName: 'Nom',
    alcoholPercentage: 'Degré %',
    volumeMl: 'Volume (ml)',
    saveForFuture: 'Sauvegarder pour utilisation future',
    timeSinceDrinking: 'Temps écoulé (optionnel)',
    minutes: 'Minutes',
    hours: 'Heures',
    calculate: 'Calculer TA',
    
    results: 'Résultats',
    bacAtMoment: 'TA au moment',
    bacAfterTime: 'TA après',
    timeToSober: 'Temps pour dessoûler',
    soberIn: 'Sobre dans',
    alreadySober: 'Déjà sobre',
    saveResult: 'Sauvegarder',
    newCalculation: 'Nouveau Calcul',
    resultSaved: 'Résultat sauvegardé!',
    
    sober: 'Sobre',
    slightImpairment: 'Légère altération',
    mildImpairment: 'Altération modérée',
    significantImpairment: 'Altération significative',
    severeImpairment: 'Altération grave',
    dangerousLevel: 'Niveau dangereux',
    
    noHistory: 'Aucun résultat sauvegardé',
    deleteConfirm: 'Supprimer ce résultat?',
    delete: 'Supprimer',
    cancel: 'Annuler',
    
    allData: 'Toutes les données',
    bacAtZeroOnly: 'TA au moment seulement',
    bacAfterTimeOnly: 'TA après temps seulement',
    filterByDate: 'Filtrer par date',
    specificDate: 'Date spécifique',
    dateRange: 'Plage de dates',
    startDate: 'Date début',
    endDate: 'Date fin',
    filterByGender: 'Filtrer par sexe',
    allGenders: 'Tous',
    apply: 'Appliquer',
    reset: 'Réinitialiser',
    noData: 'Aucune donnée disponible',
    
    theme: 'Thème',
    lightTheme: 'Clair',
    darkTheme: 'Sombre',
    language: 'Langue',
    aboutBAC: 'À propos du TA',
    bacInfo: 'Le TA (Taux d\'Alcoolémie) est la concentration d\'alcool dans le sang, mesurée en grammes par litre (g/L). Cette valeur indique le niveau d\'intoxication alcoolique.',
    howItWorks: 'Comment fonctionne le calcul',
    formulaInfo: 'Nous utilisons la formule de Widmark:\nTA = (A / (r × P)) - (β × t)\n\nOù:\n• A = alcool consommé en grammes\n• r = coefficient de distribution (0.68 hommes, 0.55 femmes)\n• P = poids corporel (kg)\n• β = taux d\'élimination (0.15 g/L/h)\n• t = temps écoulé (heures)',
    curiosities: 'Curiosités',
    curiositiesInfo: 'Le corps élimine environ 0.15 g/L d\'alcool par heure. Cela signifie qu\'il faut environ 1-2 heures pour métaboliser un verre standard.',
    privacy: 'Confidentialité',
    privacyInfo: 'Toutes les données sont sauvegardées localement sur votre appareil. Nous ne collectons ni ne partageons aucune information personnelle.',
    terms: 'Conditions d\'utilisation',
    termsInfo: 'Cette application est à titre informatif uniquement. Elle ne remplace pas un avis médical. Ne conduisez jamais après avoir bu.',
    
    errorWeight: 'Entrez un poids valide',
    errorNoDrinks: 'Ajoutez au moins une boisson',
    errorCustomDrink: 'Complétez tous les champs pour la boisson personnalisée',
    saveAsDefault: 'Enregistrer par défaut',
    savedDrinks: 'Boissons enregistrées',
    filters: 'Filtres',
    filterByTime: 'Filtrer par temps',
    allDates: 'Toutes les dates',
    bacAtMomentOnly: 'TA au moment seulement',
    bacAfterTimeOnly: 'TA après temps seulement',
  },
  
  es: {
    appTitle: 'AlcolTracker',
    appSubtitle: 'Conoce Tus Límites',
    
    tabCalculate: 'Cálculo',
    tabHistory: 'Historial',
    tabChart: 'Gráfico',
    tabSettings: 'Ajustes',
    
    weight: 'Peso (kg)',
    gender: 'Sexo',
    male: 'Hombre',
    female: 'Mujer',
    predefinedDrinks: 'Bebidas Predefinidas',
    customDrinks: 'Bebidas Personalizadas',
    beer: 'Cerveza',
    wine: 'Vino',
    spritz: 'Spritz',
    cocktail: 'Cóctel',
    liqueur: 'Licor',
    glasses: 'vasos',
    addCustomDrink: 'Añadir Bebida',
    drinkName: 'Nombre',
    alcoholPercentage: 'Graduación %',
    volumeMl: 'Volumen (ml)',
    saveForFuture: 'Guardar para uso futuro',
    timeSinceDrinking: 'Tiempo desde la bebida (opcional)',
    minutes: 'Minutos',
    hours: 'Horas',
    calculate: 'Calcular TA',
    
    results: 'Resultados',
    bacAtMoment: 'TA en el momento',
    bacAfterTime: 'TA después',
    timeToSober: 'Tiempo para estar sobrio',
    soberIn: 'Sobrio en',
    alreadySober: 'Ya sobrio',
    saveResult: 'Guardar',
    newCalculation: 'Nuevo Cálculo',
    resultSaved: '¡Resultado guardado!',
    
    sober: 'Sobrio',
    slightImpairment: 'Ligera alteración',
    mildImpairment: 'Alteración moderada',
    significantImpairment: 'Alteración significativa',
    severeImpairment: 'Alteración grave',
    dangerousLevel: 'Nivel peligroso',
    
    noHistory: 'No hay resultados guardados',
    deleteConfirm: '¿Eliminar este resultado?',
    delete: 'Eliminar',
    cancel: 'Cancelar',
    
    allData: 'Todos los datos',
    bacAtZeroOnly: 'Solo TA en el momento',
    bacAfterTimeOnly: 'Solo TA después del tiempo',
    filterByDate: 'Filtrar por fecha',
    specificDate: 'Fecha específica',
    dateRange: 'Rango de fechas',
    startDate: 'Fecha inicio',
    endDate: 'Fecha fin',
    filterByGender: 'Filtrar por sexo',
    allGenders: 'Todos',
    apply: 'Aplicar',
    reset: 'Restablecer',
    noData: 'No hay datos disponibles',
    
    theme: 'Tema',
    lightTheme: 'Claro',
    darkTheme: 'Oscuro',
    language: 'Idioma',
    aboutBAC: 'Acerca del TA',
    bacInfo: 'El TA (Tasa de Alcoholemia) es la concentración de alcohol en sangre, medida en gramos por litro (g/L). Este valor indica el nivel de intoxicación alcohólica.',
    howItWorks: 'Cómo funciona el cálculo',
    formulaInfo: 'Usamos la fórmula de Widmark:\nTA = (A / (r × P)) - (β × t)\n\nDonde:\n• A = alcohol consumido en gramos\n• r = coeficiente de distribución (0.68 hombres, 0.55 mujeres)\n• P = peso corporal (kg)\n• β = tasa de eliminación (0.15 g/L/h)\n• t = tiempo transcurrido (horas)',
    curiosities: 'Curiosidades',
    curiositiesInfo: 'El cuerpo elimina aproximadamente 0.15 g/L de alcohol por hora. Esto significa que toma alrededor de 1-2 horas metabolizar una bebida estándar.',
    privacy: 'Privacidad',
    privacyInfo: 'Todos los datos se guardan localmente en tu dispositivo. No recopilamos ni compartimos ninguna información personal.',
    terms: 'Términos de servicio',
    termsInfo: 'Esta aplicación es solo con fines informativos. No reemplaza el consejo médico. Nunca conduzcas después de beber.',
    
    errorWeight: 'Ingresa un peso válido',
    errorNoDrinks: 'Añade al menos una bebida',
    errorCustomDrink: 'Completa todos los campos para la bebida personalizada',
    saveAsDefault: 'Guardar como predeterminado',
    savedDrinks: 'Bebidas guardadas',
    filters: 'Filtros',
    filterByTime: 'Filtrar por tiempo',
    allDates: 'Todas las fechas',
    bacAtMomentOnly: 'TA al momento solamente',
    bacAfterTimeOnly: 'TA después del tiempo solamente',
  },
  
  de: {
    appTitle: 'AlcolTracker',
    appSubtitle: 'Kenne Deine Grenzen',
    
    tabCalculate: 'Berechnen',
    tabHistory: 'Verlauf',
    tabChart: 'Diagramm',
    tabSettings: 'Einstellungen',
    
    weight: 'Gewicht (kg)',
    gender: 'Geschlecht',
    male: 'Mann',
    female: 'Frau',
    predefinedDrinks: 'Vordefinierte Getränke',
    customDrinks: 'Benutzerdefinierte Getränke',
    beer: 'Bier',
    wine: 'Wein',
    spritz: 'Spritz',
    cocktail: 'Cocktail',
    liqueur: 'Likör',
    glasses: 'Gläser',
    addCustomDrink: 'Getränk Hinzufügen',
    drinkName: 'Name',
    alcoholPercentage: 'Alkoholgehalt %',
    volumeMl: 'Volumen (ml)',
    saveForFuture: 'Für zukünftige Verwendung speichern',
    timeSinceDrinking: 'Zeit seit dem Trinken (optional)',
    minutes: 'Minuten',
    hours: 'Stunden',
    calculate: 'BAK Berechnen',
    
    results: 'Ergebnisse',
    bacAtMoment: 'BAK zum Zeitpunkt',
    bacAfterTime: 'BAK nach',
    timeToSober: 'Zeit bis zur Nüchternheit',
    soberIn: 'Nüchtern in',
    alreadySober: 'Bereits nüchtern',
    saveResult: 'Speichern',
    newCalculation: 'Neue Berechnung',
    resultSaved: 'Ergebnis gespeichert!',
    
    sober: 'Nüchtern',
    slightImpairment: 'Leichte Beeinträchtigung',
    mildImpairment: 'Mäßige Beeinträchtigung',
    significantImpairment: 'Erhebliche Beeinträchtigung',
    severeImpairment: 'Schwere Beeinträchtigung',
    dangerousLevel: 'Gefährliches Niveau',
    
    noHistory: 'Keine gespeicherten Ergebnisse',
    deleteConfirm: 'Dieses Ergebnis löschen?',
    delete: 'Löschen',
    cancel: 'Abbrechen',
    
    allData: 'Alle Daten',
    bacAtZeroOnly: 'Nur BAK zum Zeitpunkt',
    bacAfterTimeOnly: 'Nur BAK nach Zeit',
    filterByDate: 'Nach Datum filtern',
    specificDate: 'Bestimmtes Datum',
    dateRange: 'Datumsbereich',
    startDate: 'Startdatum',
    endDate: 'Enddatum',
    filterByGender: 'Nach Geschlecht filtern',
    allGenders: 'Alle',
    apply: 'Anwenden',
    reset: 'Zurücksetzen',
    noData: 'Keine Daten verfügbar',
    
    theme: 'Thema',
    lightTheme: 'Hell',
    darkTheme: 'Dunkel',
    language: 'Sprache',
    aboutBAC: 'Über BAK',
    bacInfo: 'Die BAK (Blutalkoholkonzentration) ist die Konzentration von Alkohol im Blut, gemessen in Gramm pro Liter (g/L). Dieser Wert zeigt den Grad der Alkoholintoxikation an.',
    howItWorks: 'Wie die Berechnung funktioniert',
    formulaInfo: 'Wir verwenden die Widmark-Formel:\nBAK = (A / (r × P)) - (β × t)\n\nWo:\n• A = konsumierter Alkohol in Gramm\n• r = Verteilungskoeffizient (0.68 Männer, 0.55 Frauen)\n• P = Körpergewicht (kg)\n• β = Eliminationsrate (0.15 g/L/h)\n• t = verstrichene Zeit (Stunden)',
    curiosities: 'Wissenswertes',
    curiositiesInfo: 'Der Körper eliminiert etwa 0.15 g/L Alkohol pro Stunde. Das bedeutet, dass es etwa 1-2 Stunden dauert, um ein Standardgetränk zu metabolisieren.',
    privacy: 'Datenschutz',
    privacyInfo: 'Alle Daten werden lokal auf Ihrem Gerät gespeichert. Wir sammeln oder teilen keine persönlichen Informationen.',
    terms: 'Nutzungsbedingungen',
    termsInfo: 'Diese App dient nur zu Informationszwecken. Sie ersetzt keine medizinische Beratung. Fahren Sie niemals nach dem Trinken.',
    
    errorWeight: 'Geben Sie ein gültiges Gewicht ein',
    errorNoDrinks: 'Fügen Sie mindestens ein Getränk hinzu',
    errorCustomDrink: 'Füllen Sie alle Felder für das benutzerdefinierte Getränk aus',
    saveAsDefault: 'Als Standard speichern',
    savedDrinks: 'Gespeicherte Getränke',
    filters: 'Filter',
    filterByTime: 'Nach Zeit filtern',
    allDates: 'Alle Daten',
    bacAtMomentOnly: 'Nur BAK zum Zeitpunkt',
    bacAfterTimeOnly: 'Nur BAK nach Zeit',
  },
  
  ar: {
    appTitle: 'AlcolTracker',
    appSubtitle: 'اعرف حدودك',
    
    tabCalculate: 'حساب',
    tabHistory: 'السجل',
    tabChart: 'الرسم البياني',
    tabSettings: 'الإعدادات',
    
    weight: 'الوزن (كجم)',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    predefinedDrinks: 'المشروبات المحددة مسبقاً',
    customDrinks: 'المشروبات المخصصة',
    beer: 'بيرة',
    wine: 'نبيذ',
    spritz: 'سبريتز',
    cocktail: 'كوكتيل',
    liqueur: 'مشروبات كحولية',
    glasses: 'أكواب',
    addCustomDrink: 'إضافة مشروب',
    drinkName: 'الاسم',
    alcoholPercentage: 'نسبة الكحول %',
    volumeMl: 'الحجم (مل)',
    saveForFuture: 'حفظ للاستخدام المستقبلي',
    timeSinceDrinking: 'الوقت منذ الشرب (اختياري)',
    minutes: 'دقائق',
    hours: 'ساعات',
    calculate: 'حساب BAC',
    
    results: 'النتائج',
    bacAtMoment: 'BAC في اللحظة',
    bacAfterTime: 'BAC بعد',
    timeToSober: 'الوقت للصحو',
    soberIn: 'صاحٍ في',
    alreadySober: 'صاحٍ بالفعل',
    saveResult: 'حفظ النتيجة',
    newCalculation: 'حساب جديد',
    resultSaved: 'تم حفظ النتيجة!',
    
    sober: 'صاحٍ',
    slightImpairment: 'ضعف طفيف',
    mildImpairment: 'ضعف معتدل',
    significantImpairment: 'ضعف كبير',
    severeImpairment: 'ضعف شديد',
    dangerousLevel: 'مستوى خطير',
    
    noHistory: 'لا توجد نتائج محفوظة',
    deleteConfirm: 'حذف هذه النتيجة؟',
    delete: 'حذف',
    cancel: 'إلغاء',
    
    allData: 'جميع البيانات',
    bacAtZeroOnly: 'BAC في اللحظة فقط',
    bacAfterTimeOnly: 'BAC بعد الوقت فقط',
    filterByDate: 'تصفية حسب التاريخ',
    specificDate: 'تاريخ محدد',
    dateRange: 'نطاق التاريخ',
    startDate: 'تاريخ البدء',
    endDate: 'تاريخ الانتهاء',
    filterByGender: 'تصفية حسب الجنس',
    allGenders: 'الكل',
    apply: 'تطبيق',
    reset: 'إعادة تعيين',
    noData: 'لا توجد بيانات متاحة',
    
    theme: 'السمة',
    lightTheme: 'فاتح',
    darkTheme: 'داكن',
    language: 'اللغة',
    aboutBAC: 'حول BAC',
    bacInfo: 'BAC (تركيز الكحول في الدم) هو تركيز الكحول في الدم، ويُقاس بالجرام لكل لتر (جم/لتر). تشير هذه القيمة إلى مستوى التسمم بالكحول.',
    howItWorks: 'كيف يعمل الحساب',
    formulaInfo: 'نستخدم صيغة ويدمارك:\nBAC = (A / (r × P)) - (β × t)\n\nحيث:\n• A = الكحول المستهلك بالجرامات\n• r = معامل التوزيع (0.68 للذكور، 0.55 للإناث)\n• P = وزن الجسم (كجم)\n• β = معدل الإزالة (0.15 جم/لتر/ساعة)\n• t = الوقت المنقضي (ساعات)',
    curiosities: 'حقائق مثيرة',
    curiositiesInfo: 'يزيل الجسم حوالي 0.15 جم/لتر من الكحول في الساعة. هذا يعني أن الأمر يستغرق حوالي 1-2 ساعة لاستقلاب مشروب قياسي.',
    privacy: 'الخصوصية',
    privacyInfo: 'يتم حفظ جميع البيانات محلياً على جهازك. نحن لا نجمع أو نشارك أي معلومات شخصية.',
    terms: 'شروط الخدمة',
    termsInfo: 'هذا التطبيق للأغراض الإعلامية فقط. لا يحل محل المشورة الطبية. لا تقد أبداً بعد الشرب.',
    
    errorWeight: 'أدخل وزناً صالحاً',
    errorNoDrinks: 'أضف مشروباً واحداً على الأقل',
    errorCustomDrink: 'أكمل جميع الحقول للمشروب المخصص',
    saveAsDefault: 'حفظ كافتراضي',
    savedDrinks: 'المشروبات المحفوظة',
    filters: 'المرشحات',
    filterByTime: 'تصفية حسب الوقت',
    allDates: 'جميع التواريخ',
    bacAtMomentOnly: 'BAC في اللحظة فقط',
    bacAfterTimeOnly: 'BAC بعد الوقت فقط',
  },
  
  zh: {
    appTitle: 'AlcolTracker',
    appSubtitle: '了解你的极限',
    
    tabCalculate: '计算',
    tabHistory: '历史记录',
    tabChart: '图表',
    tabSettings: '设置',
    
    weight: '体重（公斤）',
    gender: '性别',
    male: '男',
    female: '女',
    predefinedDrinks: '预定义饮品',
    customDrinks: '自定义饮品',
    beer: '啤酒',
    wine: '葡萄酒',
    spritz: '气泡酒',
    cocktail: '鸡尾酒',
    liqueur: '烈酒',
    glasses: '杯',
    addCustomDrink: '添加饮品',
    drinkName: '名称',
    alcoholPercentage: '酒精度 %',
    volumeMl: '容量（毫升）',
    saveForFuture: '保存以备将来使用',
    timeSinceDrinking: '饮酒后时间（可选）',
    minutes: '分钟',
    hours: '小时',
    calculate: '计算 BAC',
    
    results: '结果',
    bacAtMoment: '当前 BAC',
    bacAfterTime: 'BAC 之后',
    timeToSober: '清醒时间',
    soberIn: '清醒于',
    alreadySober: '已经清醒',
    saveResult: '保存结果',
    newCalculation: '新计算',
    resultSaved: '结果已保存！',
    
    sober: '清醒',
    slightImpairment: '轻度受损',
    mildImpairment: '中度受损',
    significantImpairment: '显著受损',
    severeImpairment: '严重受损',
    dangerousLevel: '危险水平',
    
    noHistory: '没有保存的结果',
    deleteConfirm: '删除此结果？',
    delete: '删除',
    cancel: '取消',
    
    allData: '所有数据',
    bacAtZeroOnly: '仅当前 BAC',
    bacAfterTimeOnly: '仅时间后 BAC',
    filterByDate: '按日期过滤',
    specificDate: '特定日期',
    dateRange: '日期范围',
    startDate: '开始日期',
    endDate: '结束日期',
    filterByGender: '按性别过滤',
    allGenders: '全部',
    apply: '应用',
    reset: '重置',
    noData: '无可用数据',
    
    theme: '主题',
    lightTheme: '浅色',
    darkTheme: '深色',
    language: '语言',
    aboutBAC: '关于 BAC',
    bacInfo: 'BAC（血液酒精浓度）是血液中酒精的浓度，以克/升（g/L）为单位测量。此值表示酒精中毒的程度。',
    howItWorks: '计算如何工作',
    formulaInfo: '我们使用 Widmark 公式：\nBAC = (A / (r × P)) - (β × t)\n\n其中：\n• A = 摄入的酒精（克）\n• r = 分布系数（男性 0.68，女性 0.55）\n• P = 体重（公斤）\n• β = 消除率（0.15 克/升/小时）\n• t = 经过时间（小时）',
    curiosities: '趣闻',
    curiositiesInfo: '人体每小时消除约 0.15 克/升的酒精。这意味着代谢一份标准饮品需要约 1-2 小时。',
    privacy: '隐私',
    privacyInfo: '所有数据都保存在您的设备本地。我们不收集或共享任何个人信息。',
    terms: '服务条款',
    termsInfo: '此应用仅供参考。它不能代替医疗建议。饮酒后切勿驾驶。',
    
    errorWeight: '输入有效体重',
    errorNoDrinks: '至少添加一种饮品',
    errorCustomDrink: '完成自定义饮品的所有字段',
    saveAsDefault: '保存为默认',
    savedDrinks: '已保存的饮品',
    filters: '过滤器',
    filterByTime: '按时间过滤',
    allDates: '所有日期',
    bacAtMomentOnly: '仅当前 BAC',
    bacAfterTimeOnly: '仅时间后 BAC',
  },
  
  ja: {
    appTitle: 'AlcolTracker',
    appSubtitle: '限界を知る',
    
    tabCalculate: '計算',
    tabHistory: '履歴',
    tabChart: 'グラフ',
    tabSettings: '設定',
    
    weight: '体重（kg）',
    gender: '性別',
    male: '男性',
    female: '女性',
    predefinedDrinks: '事前定義された飲み物',
    customDrinks: 'カスタム飲み物',
    beer: 'ビール',
    wine: 'ワイン',
    spritz: 'スプリッツ',
    cocktail: 'カクテル',
    liqueur: 'リキュール',
    glasses: '杯',
    addCustomDrink: '飲み物を追加',
    drinkName: '名前',
    alcoholPercentage: 'アルコール度数 %',
    volumeMl: '容量（ml）',
    saveForFuture: '今後の使用のために保存',
    timeSinceDrinking: '飲酒後の時間（オプション）',
    minutes: '分',
    hours: '時間',
    calculate: 'BAC を計算',
    
    results: '結果',
    bacAtMoment: '現在の BAC',
    bacAfterTime: 'BAC 後',
    timeToSober: '酔いが覚めるまでの時間',
    soberIn: '酔いが覚める',
    alreadySober: 'すでに酔いが覚めている',
    saveResult: '結果を保存',
    newCalculation: '新しい計算',
    resultSaved: '結果が保存されました！',
    
    sober: '酔っていない',
    slightImpairment: '軽度の障害',
    mildImpairment: '中程度の障害',
    significantImpairment: '顕著な障害',
    severeImpairment: '重度の障害',
    dangerousLevel: '危険レベル',
    
    noHistory: '保存された結果がありません',
    deleteConfirm: 'この結果を削除しますか？',
    delete: '削除',
    cancel: 'キャンセル',
    
    allData: 'すべてのデータ',
    bacAtZeroOnly: '現在の BAC のみ',
    bacAfterTimeOnly: '時間後の BAC のみ',
    filterByDate: '日付でフィルタ',
    specificDate: '特定の日付',
    dateRange: '日付範囲',
    startDate: '開始日',
    endDate: '終了日',
    filterByGender: '性別でフィルタ',
    allGenders: 'すべて',
    apply: '適用',
    reset: 'リセット',
    noData: 'データがありません',
    
    theme: 'テーマ',
    lightTheme: 'ライト',
    darkTheme: 'ダーク',
    language: '言語',
    aboutBAC: 'BAC について',
    bacInfo: 'BAC（血中アルコール濃度）は、血液中のアルコールの濃度で、グラム/リットル（g/L）で測定されます。この値はアルコール中毒のレベルを示します。',
    howItWorks: '計算の仕組み',
    formulaInfo: 'Widmark の式を使用します：\nBAC = (A / (r × P)) - (β × t)\n\nここで：\n• A = 摂取したアルコール（グラム）\n• r = 分布係数（男性 0.68、女性 0.55）\n• P = 体重（kg）\n• β = 除去率（0.15 g/L/h）\n• t = 経過時間（時間）',
    curiosities: '豆知識',
    curiositiesInfo: '体は1時間に約 0.15 g/L のアルコールを除去します。つまり、標準的な飲み物を代謝するのに約 1-2 時間かかります。',
    privacy: 'プライバシー',
    privacyInfo: 'すべてのデータはデバイスにローカルに保存されます。個人情報は収集または共有しません。',
    terms: '利用規約',
    termsInfo: 'このアプリは情報提供のみを目的としています。医学的アドバイスに代わるものではありません。飲酒後は絶対に運転しないでください。',
    
    errorWeight: '有効な体重を入力してください',
    errorNoDrinks: '少なくとも1つの飲み物を追加してください',
    errorCustomDrink: 'カスタム飲み物のすべてのフィールドを完成させてください',
    saveAsDefault: 'デフォルトとして保存',
    savedDrinks: '保存された飲み物',
    filters: 'フィルター',
    filterByTime: '時間でフィルタ',
    allDates: 'すべての日付',
    bacAtMomentOnly: '現在の BAC のみ',
    bacAfterTimeOnly: '時間後の BAC のみ',
  },
  
  ko: {
    appTitle: 'AlcolTracker',
    appSubtitle: '한계를 알아보세요',
    
    tabCalculate: '계산',
    tabHistory: '기록',
    tabChart: '차트',
    tabSettings: '설정',
    
    weight: '체중 (kg)',
    gender: '성별',
    male: '남성',
    female: '여성',
    predefinedDrinks: '사전 정의된 음료',
    customDrinks: '맞춤 음료',
    beer: '맥주',
    wine: '와인',
    spritz: '스프리츠',
    cocktail: '칵테일',
    liqueur: '리큐어',
    glasses: '잔',
    addCustomDrink: '음료 추가',
    drinkName: '이름',
    alcoholPercentage: '알코올 도수 %',
    volumeMl: '용량 (ml)',
    saveForFuture: '향후 사용을 위해 저장',
    timeSinceDrinking: '음주 후 시간 (선택 사항)',
    minutes: '분',
    hours: '시간',
    calculate: 'BAC 계산',
    
    results: '결과',
    bacAtMoment: '현재 BAC',
    bacAfterTime: 'BAC 이후',
    timeToSober: '깨는 시간',
    soberIn: '깨는 시간',
    alreadySober: '이미 깼습니다',
    saveResult: '결과 저장',
    newCalculation: '새 계산',
    resultSaved: '결과가 저장되었습니다!',
    
    sober: '깬 상태',
    slightImpairment: '경미한 손상',
    mildImpairment: '중간 손상',
    significantImpairment: '상당한 손상',
    severeImpairment: '심각한 손상',
    dangerousLevel: '위험 수준',
    
    noHistory: '저장된 결과가 없습니다',
    deleteConfirm: '이 결과를 삭제하시겠습니까?',
    delete: '삭제',
    cancel: '취소',
    
    allData: '모든 데이터',
    bacAtZeroOnly: '현재 BAC만',
    bacAfterTimeOnly: '시간 후 BAC만',
    filterByDate: '날짜별 필터',
    specificDate: '특정 날짜',
    dateRange: '날짜 범위',
    startDate: '시작 날짜',
    endDate: '종료 날짜',
    filterByGender: '성별별 필터',
    allGenders: '모두',
    apply: '적용',
    reset: '재설정',
    noData: '사용 가능한 데이터가 없습니다',
    
    theme: '테마',
    lightTheme: '라이트',
    darkTheme: '다크',
    language: '언어',
    aboutBAC: 'BAC 정보',
    bacInfo: 'BAC (혈중 알코올 농도)는 혈액 내 알코올 농도로, 그램/리터 (g/L)로 측정됩니다. 이 값은 알코올 중독 수준을 나타냅니다.',
    howItWorks: '계산 방법',
    formulaInfo: 'Widmark 공식을 사용합니다:\nBAC = (A / (r × P)) - (β × t)\n\n여기서:\n• A = 섭취한 알코올 (그램)\n• r = 분포 계수 (남성 0.68, 여성 0.55)\n• P = 체중 (kg)\n• β = 제거율 (0.15 g/L/h)\n• t = 경과 시간 (시간)',
    curiosities: '흥미로운 사실',
    curiositiesInfo: '신체는 시간당 약 0.15 g/L의 알코올을 제거합니다. 즉, 표준 음료를 대사하는 데 약 1-2시간이 걸립니다.',
    privacy: '개인정보',
    privacyInfo: '모든 데이터는 기기에 로컬로 저장됩니다. 개인 정보를 수집하거나 공유하지 않습니다.',
    terms: '서비스 약관',
    termsInfo: '이 앱은 정보 제공 목적으로만 사용됩니다. 의학적 조언을 대체하지 않습니다. 음주 후 절대 운전하지 마십시오.',
    
    errorWeight: '유효한 체중을 입력하세요',
    errorNoDrinks: '최소 하나의 음료를 추가하세요',
    errorCustomDrink: '맞춤 음료의 모든 필드를 완성하세요',
    saveAsDefault: '기본값으로 저장',
    savedDrinks: '저장된 음료',
    filters: '필터',
    filterByTime: '시간별 필터',
    allDates: '모든 날짜',
    bacAtMomentOnly: '현재 BAC만',
    bacAfterTimeOnly: '시간 후 BAC만',
  },
  
  pt: {
    appTitle: 'AlcolTracker',
    appSubtitle: 'Conheça Seus Limites',
    
    tabCalculate: 'Calcular',
    tabHistory: 'Histórico',
    tabChart: 'Gráfico',
    tabSettings: 'Configurações',
    
    weight: 'Peso (kg)',
    gender: 'Sexo',
    male: 'Homem',
    female: 'Mulher',
    predefinedDrinks: 'Bebidas Predefinidas',
    customDrinks: 'Bebidas Personalizadas',
    beer: 'Cerveja',
    wine: 'Vinho',
    spritz: 'Spritz',
    cocktail: 'Coquetel',
    liqueur: 'Licor',
    glasses: 'copos',
    addCustomDrink: 'Adicionar Bebida',
    drinkName: 'Nome',
    alcoholPercentage: 'Teor Alcoólico %',
    volumeMl: 'Volume (ml)',
    saveForFuture: 'Salvar para uso futuro',
    timeSinceDrinking: 'Tempo desde a bebida (opcional)',
    minutes: 'Minutos',
    hours: 'Horas',
    calculate: 'Calcular TAS',
    
    results: 'Resultados',
    bacAtMoment: 'TAS no momento',
    bacAfterTime: 'TAS depois',
    timeToSober: 'Tempo para ficar sóbrio',
    soberIn: 'Sóbrio em',
    alreadySober: 'Já sóbrio',
    saveResult: 'Salvar Resultado',
    newCalculation: 'Novo Cálculo',
    resultSaved: 'Resultado salvo!',
    
    sober: 'Sóbrio',
    slightImpairment: 'Comprometimento leve',
    mildImpairment: 'Comprometimento moderado',
    significantImpairment: 'Comprometimento significativo',
    severeImpairment: 'Comprometimento grave',
    dangerousLevel: 'Nível perigoso',
    
    noHistory: 'Nenhum resultado salvo',
    deleteConfirm: 'Excluir este resultado?',
    delete: 'Excluir',
    cancel: 'Cancelar',
    
    allData: 'Todos os dados',
    bacAtZeroOnly: 'Apenas TAS no momento',
    bacAfterTimeOnly: 'Apenas TAS após tempo',
    filterByDate: 'Filtrar por data',
    specificDate: 'Data específica',
    dateRange: 'Intervalo de datas',
    startDate: 'Data inicial',
    endDate: 'Data final',
    filterByGender: 'Filtrar por sexo',
    allGenders: 'Todos',
    apply: 'Aplicar',
    reset: 'Redefinir',
    noData: 'Nenhum dado disponível',
    
    theme: 'Tema',
    lightTheme: 'Claro',
    darkTheme: 'Escuro',
    language: 'Idioma',
    aboutBAC: 'Sobre TAS',
    bacInfo: 'TAS (Taxa de Alcoolemia no Sangue) é a concentração de álcool no sangue, medida em gramas por litro (g/L). Este valor indica o nível de intoxicação alcoólica.',
    howItWorks: 'Como funciona o cálculo',
    formulaInfo: 'Usamos a fórmula de Widmark:\nTAS = (A / (r × P)) - (β × t)\n\nOnde:\n• A = álcool consumido em gramas\n• r = coeficiente de distribuição (0.68 homens, 0.55 mulheres)\n• P = peso corporal (kg)\n• β = taxa de eliminação (0.15 g/L/h)\n• t = tempo decorrido (horas)',
    curiosities: 'Curiosidades',
    curiositiesInfo: 'O corpo elimina cerca de 0.15 g/L de álcool por hora. Isso significa que leva cerca de 1-2 horas para metabolizar uma bebida padrão.',
    privacy: 'Privacidade',
    privacyInfo: 'Todos os dados são salvos localmente no seu dispositivo. Não coletamos nem compartilhamos nenhuma informação pessoal.',
    terms: 'Termos de serviço',
    termsInfo: 'Este aplicativo é apenas para fins informativos. Não substitui aconselhamento médico. Nunca dirija depois de beber.',
    
    errorWeight: 'Insira um peso válido',
    errorNoDrinks: 'Adicione pelo menos uma bebida',
    errorCustomDrink: 'Complete todos os campos para a bebida personalizada',
    saveAsDefault: 'Salvar como padrão',
    savedDrinks: 'Bebidas salvas',
    filters: 'Filtros',
    filterByTime: 'Filtrar por tempo',
    allDates: 'Todas as datas',
    bacAtMomentOnly: 'Apenas TAS no momento',
    bacAfterTimeOnly: 'Apenas TAS após tempo',
  },
};